# Generated by Django 3.2 on 2022-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_adver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adver',
            options={'verbose_name': 'تبلیغ', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AddField(
            model_name='adver',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
    ]
