# Generated by Django 3.2 on 2022-11-24 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('09(1[0-9]|3[0-9]|2[0-9])-?[0-9]{3}-?[0-9]{4}')]),
        ),
    ]
